AllCops:
  Exclude:
    - 'bin/*'

Metrics/LineLength:
  Max: 140

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/NonDeterministicRequireOrder:
  Enabled: false
